(tests
 (names
  test_parse
  test_normalize
  test_dominator
  test_construct
  test_loopnesting
  test_deadcode
  test_constprop
  test_undag
  test_select_x86
  test_spill
  test_execfreq)
 (modes
  (byte exe))
 (flags (:standard))
 (preprocess
  (pps ppx_deriving.std))
 (libraries alcotest baby_pascal logs.fmt))
